# Generated by Django 2.1.7 on 2019-03-16 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
