# Generated by Django 2.1.7 on 2019-03-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlepost_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
